### ISSUE TITLE
yarn install not finding react-native-image-gallery

### ISSUE THREAD

**Issue by simbadMarino** [martymfly/expo-file-manager#1]
Hello @martymfly ,

Looks like we have a missing package here, would you please support?

Log after I perform a yarn install:

yarn install
yarn install v1.22.18
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/martymfly/react-native-image-gallery/tar.gz/f33ff11e4decfecfe8e7e0697ce0306933972ba8: Request failed \"404 Not Found\"".

Thank you!

**Comment by martymfly** [comment]
Hi @simbadMarino , there were some changes I made to the original react-native-image-gallery library but apparently I somehow removed that repo. I've just pushed a fix for changing the package. I'll later on look for another alternative which is better maintained.

**Comment by simbadMarino** [comment]
thank you! worked like a charm =)
