### ISSUE TITLE
FEATURE: Add additional properties on items

### ISSUE THREAD

**Issue by simbadMarino** [martymfly/expo-file-manager#2]
Hello, more than an issue this is a question, do you know if its posssible to include additional properties to items? 
Right now we have for example item.uri, item.name, etc.

I need to include an additional property to each file items so later on I can access such property by calling e.g.: item.location or item.color
I want to avoid the need of storing such data in a differen database/list.

I have tried to modify certain parameters in the FileItem.tsx , types.d.ts, Browser.tsx but but could not locate how.

If you could support on this I'd greatly appreciate it

**Comment by martymfly** [comment]
> Hello, more than an issue this is a question, do you know if its posssible to include additional properties to items? Right now we have for example item.uri, item.name, etc.
> 
> I need to include an additional property to each file items so later on I can access such property by calling e.g.: item.location or item.color I want to avoid the need of storing such data in a differen database/list.
> 
> I have tried to modify certain parameters in the FileItem.tsx , types.d.ts, Browser.tsx but but could not locate how.
> 
> If you could support on this I'd greatly appreciate it

Hello,

I made a quick research on adding custom metadata to files but I couldn't find a way. There are suggestions on storing the custom metadata in an sqlite db or in sharedpreferences. I would give it a try with a key-value storage.

https://github.com/mrousavy/react-native-mmkv

**Comment by simbadMarino** [comment]
Thanks for the prompt reply! I will definetely check the reference you pointed out, still learning react native :)

**Comment by martymfly** [comment]
> Thanks for the prompt reply! I will definetely check the reference you pointed out, still learning react native :)

Not at all! I'm glad that someone is interested in the repo :) Feel free to create a pr with your implementation! :)
